stacktrace: label followed by a declaration is a C23 extension
clang 22 complains about a label followed by a declaration in
src/stacktrace.c because it doesn't default to C23.

src/stacktrace.c:913:3: error: label followed by a declaration is a
C23 extension [-Werror,-Wc23-extensions]
  913 |   bool is_abi32 = (regs->abi == PERF_SAMPLE_REGS_ABI_32);
      |   ^

This isn't a problem with gcc because it is a GNU extension.

	* src/stacktrace.c (sysprof_find_dwfl): But declarations after
	reuse label into block.

Signed-off-by: Mark Wielaard <mark@klomp.org>